CREATE TABLE book(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    stock SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    isbn CHAR(13) NOT NULL,
    price FLOAT
)